Treesitter Highlight Maps + Aerial fix
catppuccin/nvim pull request #310
Opened 2022-10-19 04:42 UTC by axieax

This PR refactors to use Treesitter highlight group mappings, and resolves #307.

2022-10-19 05:55 UTC, nullchilly commented
Why didn you delete `TS*` highlights group despite adding a fallback to nvim 0.7?

2022-10-19 06:05 UTC, nullchilly commented on lua/catppuccin/groups/integrations/treesitter.lua
> -			-- yaml
I meant restore this table so the fallback map actually works

Please test these changes on nvim 0.7.2 appimage

2022-10-19 06:06 UTC, axieax commented
My intent is to migrate to the new Treesitter highlight syntax, but also add a fallback for the old way `TS*`. This mapping refactor reduces repeated code and allows for future development to use the new syntax.

2022-10-19 06:06 UTC, nullchilly commented
@axieax You are missing the point.

You deleted the old TS* group in nvim 0.7, there is nothing to fallback into

2022-10-19 06:09 UTC, axieax commented
> @axieax You are missing the point.
> 
> You deleted the old TS* group in nvim 0.7, there is nothing to fallback into

Doesn't this simply map the new syntax to the old syntax?

https://github.com/axieax/catppuccin-nvim/blob/9c5f806a04b8d40dafdc2c877703071ce7323381/lua/catppuccin/groups/integrations/treesitter.lua#L115-L123

2022-10-19 06:14 UTC, nullchilly commented
@axieax Ah yeah, you're right 😅

Reviewing on phone is hard

@gotgenes Would you mind testing this pull request?

2022-10-19 18:41 UTC, nullchilly commented
@axieax [Wait...](https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f#), its actually still broken as treesitter no longer support `TS*` highlights. Why do we care so much about legacy fallback to `TS*` when nvim-treesitter itself now requires nvim 0.8?

2022-10-19 20:01 UTC, axieax commented
Yeah I get what you mean. Do you think it's better if we remove the mapping altogether and only support the updated syntax?

2022-10-20 02:00 UTC, nullchilly commented
@axieax Maybe something like this?

```lua
if vim.treesitter.highlighter.hl_map then
  vim.notify([[Catppuccin (info):
nvim-treesitter integration requires neovim 0.8
If you want to stay on nvim 0.7 disable the integration or pin catppuccin tag to v0.2.4 and nvim-treesitter to ...
]], "info")
```

2022-10-20 03:30 UTC, axieax commented
Should be ready now :))

2022-10-20 16:16 UTC, nullchilly requested changes

2022-10-21 02:02 UTC, axieax commented
Addressed!

2022-10-21 02:09 UTC, merged