feat: add support for transparent background with Tresitter Context i…
catppuccin/nvim pull request #519
Opened 2023-06-22 16:19 UTC by joshmedeski

Updates the Treesitter Context plugin to use a transparent background if transparent_background was set.

2023-06-22 16:35 UTC, nullchilly commented
treesitter_context integration is not enabled by default and thus support transparent background out of the box

The reason the integration still exists is https://github.com/catppuccin/nvim/issues/445

2023-06-22 16:45 UTC, joshmedeski commented
Okay, I won't enable the integration so I can get transparency.

Do you think I should update this PR to add a code comment mentioning that enabling this integration makes it distinguishable when transparency is enabled? That is unclear when looking at the source-code. It just appears to be a missing feature.

If not, feel free to just close the PR.

2023-06-22 16:46 UTC, nullchilly commented
I think we can change it to use `TreesitterContextBottom` if transparency is enabled

2023-06-22 16:49 UTC, nullchilly commented
I think we can define `hi TreesitterContextBottom gui=underline guisp=Grey` when transparency is enabled

![image](https://github.com/catppuccin/nvim/assets/56817415/a444491a-faf6-4c7b-8ca1-6b6807c7a60c)

2023-06-22 17:01 UTC, nullchilly requested changes

2023-06-22 17:12 UTC, joshmedeski commented on lua/catppuccin/groups/integrations/treesitter_context.lua
> +		TreesitterContextBottom = { gui = "underline", guisp = C.dim },
Sounds good, I updated it.

2023-06-22 17:21 UTC, nullchilly commented
LGTM!

2023-06-23 00:57 UTC, mrtnvgr approved these changes
LGTM!

2023-06-24 11:50 UTC, merged