feat(blink-cmp): improve styling support
catppuccin/nvim pull request #809
Opened 2024-12-10 14:30 UTC by milkias17

add hl groups for BlinkCmpKind, BlinkCmpMenu, BlinkCmpMenuBorder, BlinkCmpDocBorder, BlinkCmpSignatureHelpActiveParameter

- This was the previous styling for blink.cmp, it didn't have the correct background color for the completion menu, no border styling and no styling for showing the current signaturehelp item.
![Screenshot_20241210_163953](https://github.com/user-attachments/assets/72e68850-7188-4288-be3b-70630487cc10)

- This is how it looks after the new hl group additions:
![image](https://github.com/user-attachments/assets/0ff0bce4-f0a4-4dd0-9060-ada22555922e)

- All styling colors were taken from previous nvim-cmp styling and the catppuccin vscode theme.

2025-01-07 18:36 UTC, milkias17 commented on lua/catppuccin/groups/integrations/blink_cmp.lua
> +		BlinkCmpSignatureHelpActiveParameter = { fg = C.mauve },
My bad, have added it now

2025-01-30 11:33 UTC, vollowx commented
By default we assume that the user uses the un-bordered UI and apply the colors for that, if you still want to support the bordered UI, please add a option named `bordered` and seperate the highlight groups.

2025-01-30 13:31 UTC, milkias17 commented
@vollowx Perhaps I'm missing something, and correct me if I'm wrong here.

BlinkCmpMenuBorder highlight group only takes effect when someone enables the bordered UI, otherwise there's no difference in the UI for the user. And you said we apply the colors for that, however I'm not changing an existing highlight group, the BlinkCmpMenuBorder highlight group doesn't exist in the current blink.cmp integration.

So I'm having trouble understanding your objection, would love to be corrected if I'm missing something tho.

2025-02-01 04:16 UTC, vollowx requested changes

2025-02-01 04:16 UTC, vollowx commented on lua/catppuccin/groups/integrations/blink_cmp.lua
> +		BlinkCmpMenu = { fg = C.text },
I was looking at the screenshots and found that the background has been reset, and I think it is this line that changed the background. You probably need to explicitly declare the background color in this case.

2025-02-01 06:48 UTC, milkias17 commented on lua/catppuccin/groups/integrations/blink_cmp.lua
> +		BlinkCmpMenu = { fg = C.text },
I'm not sure what exactly you mean by "the background has been reset", the current blink.cmp integration doesn't set the background color of the completion menu(the screenshot at the top), what I did was change the background of the menu to be reflective of the catppuccin colors.

The appearance of the menu(with the catppuccin background) is the exact same ui that's in place for nvim-cmp

2025-02-02 07:58 UTC, vollowx commented on lua/catppuccin/groups/integrations/blink_cmp.lua
> +		BlinkCmpMenu = { fg = C.text },
By default, according to [this line](https://github.com/Saghen/blink.cmp/blob/main/lua/blink/cmp/highlights.lua#L32) in blink.cmp, the `BlinkCmpMenu` is set to be the same as `Pmenu`, which has a background color of darkened `surface0` according to [this line](https://github.com/catppuccin/nvim/blob/4965db2d6155c25db4e8417465fc2703fdf4c2b7/lua/catppuccin/groups/editor.lua#L44). After defining the `BlinkCmpMenu` manually without setting the background color, the background becomes `base`, which doesn't look good when using the un-bordered UI.

2025-06-07 04:49 UTC, closed without merging